### ISSUE TITLE
2024/08/25 在使用过程中报错

### ISSUE THREAD

**Issue by xiaosuan2b** [Coaixy/weiban-tool#22]
关键日志：
资源加载完成
1 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
2 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
3 / 40

完整日志：
编号 -  课程
-----------------------
0    -  2024年本科生新生安全教育

已经识别到唯一项目, 请直接输入“0”开始执行: 0
是否自动考试: 0: 不自动考试, >0 : 考试时间(单位秒)0
当前项目名称:  2024年本科生新生安全教育
加载章节 : 国家安全各个方面
加载章节 : 总体国家安全观总论
加载章节 : 安全第一课
加载章节 : 安全文化
加载章节 : 艾滋病防治
加载章节 : 急救知识
加载章节 : 身体健康
加载章节 : 应对突发事件
加载章节 : 禁毒教育
加载章节 : 防范诈骗
加载章节 : 交通安全
加载章节 : 人身安全
加载章节 : 网络安全
加载章节 : 消防安全
加载章节 : 学业安全
加载章节 : 报到路途安全
加载章节 : 大学生家长必学
加载章节 : 心理健康
加载章节 : 人际交往
加载章节 : 恋爱与性知识
加载章节 : 诚信与法律

资源加载完成
加载章节 : 总体国家安全观总论
加载章节 : 安全第一课
加载章节 : 安全文化
加载章节 : 身体健康
加载章节 : 应对突发事件
加载章节 : 禁毒教育
加载章节 : 防范诈骗
加载章节 : 网络安全
加载章节 : 消防安全
加载章节 : 报到路途安全
加载章节 : 心理健康
加载章节 : 人际交往
加载章节 : 恋爱与性知识
加载章节 : 诚信与法律

资源加载完成
1 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
2 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
3 / 40

**Comment by Coaixy** [comment]
群内有替换方案

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xiaosuan2b ***@***.***>
发送时间: Sunday, August 25, 2024 1:30:26 PM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Coaixy/weiban-tool] 2024/08/25 在使用过程中报错 (Issue #22)


关键日志：
资源加载完成
1 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
2 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
3 / 40

完整日志：
编号 - 课程

0 - 2024年本科生新生安全教育

已经识别到唯一项目, 请直接输入“0”开始执行: 0
是否自动考试: 0: 不自动考试, >0 : 考试时间(单位秒)0
当前项目名称: 2024年本科生新生安全教育
加载章节 : 国家安全各个方面
加载章节 : 总体国家安全观总论
加载章节 : 安全第一课
加载章节 : 安全文化
加载章节 : 艾滋病防治
加载章节 : 急救知识
加载章节 : 身体健康
加载章节 : 应对突发事件
加载章节 : 禁毒教育
加载章节 : 防范诈骗
加载章节 : 交通安全
加载章节 : 人身安全
加载章节 : 网络安全
加载章节 : 消防安全
加载章节 : 学业安全
加载章节 : 报到路途安全
加载章节 : 大学生家长必学
加载章节 : 心理健康
加载章节 : 人际交往
加载章节 : 恋爱与性知识
加载章节 : 诚信与法律

资源加载完成
加载章节 : 总体国家安全观总论
加载章节 : 安全第一课
加载章节 : 安全文化
加载章节 : 身体健康
加载章节 : 应对突发事件
加载章节 : 禁毒教育
加载章节 : 防范诈骗
加载章节 : 网络安全
加载章节 : 消防安全
加载章节 : 报到路途安全
加载章节 : 心理健康
加载章节 : 人际交往
加载章节 : 恋爱与性知识
加载章节 : 诚信与法律

资源加载完成
1 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
2 / 40
{"msg":"参数不合法","code":"-1","detailCode":"-2"}
3 / 40

―

**Comment by Coaixy** [comment]
[WeiBanHelper.py.zip](https://github.com/user-attachments/files/16739543/WeiBanHelper.py.zip)
替换这个文件
