### ISSUE TITLE
加群讨论的图好像无了

### ISSUE THREAD

**Issue by Nichovlasy** [Coaixy/weiban-tool#3]
加群讨论:https://jcdn.lawliet.ren/qrcode.jpg

**Comment by Coaixy** [comment]
群聊不再提供，有问题可以issue或者发我邮件

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Nichovlasy ***@***.***>
发送时间: Monday, August 5, 2024 1:11:50 PM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Coaixy/weiban-tool] 加群讨论的图好像无了 (Issue #3)


加群讨论:https://jcdn.lawliet.ren/qrcode.jpg

―
