### ISSUE TITLE
无法自动考试

### ISSUE THREAD

**Issue by kucaozyx** [Coaixy/weiban-tool#42]
资源加载完成
chooseType=3 的课程刷课完成
但考试没有完成

**Comment by Coaixy** [comment]
参数怎么填的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kucaozyx ***@***.***>
发送时间: Tuesday, September 17, 2024 11:00:04 AM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Coaixy/weiban-tool] 无法自动考试 (Issue #42)


资源加载完成
chooseType=3 的课程刷课完成
但考试没有完成

―

**Comment by kucaozyx** [comment]
0    -  2024级新生安全教育


已经识别到唯一项目, 请直接输入“0”开始执行: 0
是否自动考试: 0: 不自动考试, >0 : 考试时间(单位秒)0
当前项目名称:  2024级新生安全教育

资源加载完成
chooseType=2 的课程刷课完成

资源加载完成
chooseType=3 的课程刷课完成
但是打开看后没有考试

**Comment by Coaixy** [comment]
0是不考试，

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kucaozyx ***@***.***>
发送时间: Tuesday, September 17, 2024 11:08:08 AM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Chen YiJie ***@***.***>; Comment ***@***.***>
主题: Re: [Coaixy/weiban-tool] 无法自动考试 (Issue #42)


0 - 2024级新生安全教育

已经识别到唯一项目, 请直接输入“0”开始执行: 0
是否自动考试: 0: 不自动考试, >0 : 考试时间(单位秒)0
当前项目名称: 2024级新生安全教育

资源加载完成
chooseType=2 的课程刷课完成

资源加载完成
chooseType=3 的课程刷课完成
但是打开看后没有考试

―
