### ISSUE TITLE
安装环境时，无法安装DateTime，ddddocr。

### ISSUE THREAD

**Issue by wdmxscg** [Coaixy/weiban-tool#45]
**# 安装环境时，无法安装DateTime，ddddocr。**
以下是我的conda命令（除了以上两个包）：conda create --prefix E:\SoftwareData\AnacondaPythonEnvironments\Weiban-Tool python=3.8 requests Pillow pycryptodomex fastapi uvicorn

**Comment by Coaixy** [comment]
使用python3.11

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wdmxscg ***@***.***>
发送时间: Thursday, September 19, 2024 3:26:58 PM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Coaixy/weiban-tool] 安装环境时，无法安装DateTime，ddddocr。 (Issue #45)


# 安装环境时，无法安装DateTime，ddddocr。
以下是我的conda命令（除了以上两个包）：conda create --prefix E:\SoftwareData\AnacondaPythonEnvironments\Weiban-Tool python=3.8 requests Pillow pycryptodomex fastapi uvicorn

―
