### ISSUE TITLE
关于 #56 的一些问题

### ISSUE THREAD

**Issue by Seeridia** [Coaixy/weiban-tool#57]
#56 中增加对ai答题的支持，而其正确率无法保证，最好在提交前提示用户相关信息（不用match_count，加一个变量统计ai做题数量，然后提示用户）

![相关代码](https://github.com/Coaixy/weiban-tool/blob/36b9b23eac75d9052927ea035c6d40f60fff2e3b/WeiBanHelper.py#L547)

**Comment by Seeridia** [comment]
算了 我自己先改改看吧

**Comment by Coaixy** [comment]
对的，Ai做的不一定对

**Comment by Seeridia** [comment]
> 但其实一般用户用不太到ai

这倒是 配置都很麻烦了
