### ISSUE TITLE
不是当前任务的项目如何添加

### ISSUE THREAD

**Issue by winterspuppy** [Coaixy/weiban-tool#59]
![image](https://github.com/user-attachments/assets/d603d692-5656-469b-a616-6569f263e38e)
这是之前忘记做了，今年秋季的已经刷完了（用的就是这个！感谢感谢），想知道像这种不是当前任务的项目怎么添加进去。（我翻了之前的issue，也翻阅了源码，不知道如何添加）

**Comment by Coaixy** [comment]
https://github.com/Coaixy/weiban-tool/blob/6388f54e420fb8e7b0b56423304e881c2be49184/WeiBanHelper.py#L341

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: winterspuppy ***@***.***>
发送时间: Tuesday, December 3, 2024 10:44:03 PM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Coaixy/weiban-tool] 不是当前任务的项目如何添加 (Issue #59)


Reopened #59<https://github.com/Coaixy/weiban-tool/issues/59>.

―
